# Generated by Django 4.1.4 on 2022-12-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubuser', models.CharField(max_length=1000)),
                ('githubuserimage', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
            ],
        ),
    ]
